# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - env:
    - CGO_ENABLED=0
    main: ./cmd/xtag/
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
brew:
  github:
    owner: haya14busa
    name: homebrew-xtag
  folder: Formula
  homepage:  https://github.com/haya14busa/xtag
  description: Finds latest release tag which matched with given tag with x wild card (a.k.a. xtag).
  test: |
    system "#{bin}/xtag -h"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
